# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master"]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.3'

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test ./... -v 
      
      - name: Analyze Test Results
        if: failure() 
        run: go test./.. -v | sed ''/PASS/s//$(printf "\033[32mPASS\033[0m")/'' | sed ''/FAIL/s//$(printf "\033[31mFAIL\033[0m")/'' && 
          go test ./... -v > test-output.log &&
          if grep -q "FAIL" test-output.log; then
            echo "Tests failed"
            exit 1
          else
            echo "All tests passed"
          fi  

      - name: Code Coverage Test
        if: success()
        run: go test -coverprofile=coverage.out ./... && go tool cover -html=coverage.out

      